#!/usr/bin/env python3
"""Generate oled_sim input decks for the whole PhD TCAD validation set.

Device: 100 nm single-layer F8BT, EGDM transport, T = 300 K, 0 -> 10 V.
  HOMO 5.9 eV, LUMO 3.3 eV  -> Eg = 2.6 eV, Xi = 3.3 eV
  sigma = 0.15 eV (both the DOS width and the EGDM disorder parameter)
  mu0p = 0.1 cm^2/Vs fixed; mu0n swept 1e-3 / 1e-2 / 1e-1 cm^2/Vs
  Electron traps: exponential tail, N_T = 7.5e17 cm^-3, T_t = 780 K
  Cathode 2.9 eV, ohmic (0.4 eV above the LUMO)
  Anode work function swept 4.9 -> 6.3 eV, one folder each

Contact models
--------------
The 4.9-5.6 eV anodes are thermionic (Scott-Malliaras), barrier = HOMO - WF.
The 6.3 eV anode is OHMIC, like the cathode: the reference holds p(x=0) at
exactly 5e20 cm^-3 = N0/2 at every bias and every mu0n, which is a pinned
ohmic-np contact rather than an injection-limited one.

Parameter provenance (the three values not given directly)
----------------------------------------------------------
N0 = 1e27 m^-3 (1e21 cm^-3) site density, both bands.  Fitted from the
reference contact densities: the 6.3 eV ohmic anode saturates at exactly
N0/2 (a half-filled Gaussian), and the thermionic-anode densities across all
seven work functions follow the Gaussian-DOS Fermi integral to 1-2% with this
N0 and plain Fermi-Dirac occupation.  The sub-Boltzmann, decreasing slope of
ln(p) against work function is what rules out Boltzmann statistics.

EGDM prefactor: the reference tool defines
    mu = mu0 * exp(-0.42*sigma_hat^2) * g1(n) * g2(F),
whereas src/mobility.c follows Pasveer eq. (3) literally and carries an extra
c1 = 1.8e-9.  Dividing by c1 makes this deck's `mun`/`mup` mean the same mu0
the reference does.  Confirmed by the user, and verified numerically against
Mobilities_5d5_0d001_5V_data.txt.

Reduced Langevin gamma = 0.1: confirmed by the user as the value used in the
TCAD software.  Full Langevin sweeps the minority electrons out far too
efficiently and drives n(x) in the anode half orders of magnitude low.
"""
import os

KB_EV = 8.617333262e-5
HOMO, LUMO = 5.9, 3.3
SIGMA = 0.15
N0 = 1e27              # m^-3, site density (both bands)
THICK = 100e-9
T_TRAP = 780.0
NT_TRAP = 7.5e23       # m^-3, the TOTAL trap density N_T
CATHODE_WF = 2.9
HERE = os.path.dirname(os.path.abspath(__file__))

# folder label -> anode work function [eV].  The 6.3 eV device is ohmic.
ANODES = {"4d9": 4.9, "5d1": 5.1, "5d2": 5.2, "5d3": 5.3,
          "5d5": 5.5, "5d6": 5.6, "6d3": 6.3}
OHMIC_ANODES = {"6d3"}

# deck label -> mu0n [cm^2/Vs]
MU0N = {"0d001": 1e-3, "0d01": 1e-2, "0d1": 1e-1}
MU0P = 1e-1

EGDM_C1 = 1.8e-9       # see the EGDM note in the module docstring
LANGEVIN_PRE = 0.1     # reduced Langevin, as used in the reference tool

TEMPLATE = """\
# F8BT 100 nm EGDM - PhD TCAD validation
#   anode {wf} eV ({amodel}), cathode {cwf} eV (ohmic), mu0n = {mun_cm} cm2/Vs
# Generated by ../make_decks.py; see that file for the parameter provenance.

[simulation]
T = 300
voltage_start = 0.0
voltage_stop = 10.0
voltage_step = 0.1
points_per_layer = 100
newton_tol = 1e-9
newton_tol_relaxed = 1e-6
max_newton_steps = 500
newton_clamp = 4.0
output_dir = {outdir}

[layer f8bt]
thickness = {thick}
Eg = {eg}
Xi = {xi}
epsilon_r = 3.0
Nc = {n0}
Nv = {n0}
statistics = gaussian
dos_sigma_e = {sigma}
dos_sigma_h = {sigma}

mobility_model_e = egdm
mobility_model_h = egdm
mun = {mun}
mup = {mup}
egdm_sigma_e = {sigma}
egdm_sigma_h = {sigma}
egdm_a_e = {a}
egdm_a_h = {a}
egdm_Nt_e = {n0}
egdm_Nt_h = {n0}

recomb_model = langevin
langevin_pre = {lpre}

# electron tail traps: total N_T = 7.5e17 cm^-3 (T_t = 780 K).
# trap_Nt_e is the tail DOS PREFACTOR [m^-3 eV^-1]; the total is
# trap_Nt_e * trap_Et_e, so the prefactor below is N_T / Et.
trap_model_e = exponential
trap_Nt_e = {nt}
trap_Et_e = {et:.6f}
trap_model_h = none
srh_bands = 8
srh_start = -0.8
srh_sigman_e = 1e-20
srh_sigmap_e = 1e-20
srh_vth = 1e5

[contact_anode]
majority = hole
{anode_block}

[contact_cathode]
model = ohmic-np
majority = electron
np = {cnp}

[outcoupling]
enabled = 0
"""


def main():
    a = (1.0 / N0) ** (1.0 / 3.0)          # inter-site distance from site density
    et = T_TRAP * KB_EV                     # exponential tail energy [eV]
    # `trap_Nt_e` is the PREFACTOR of the exponential tail DOS,
    #     rho(E) = trap_Nt_e * exp(E/Et)   [m^-3 eV^-1],
    # so the density it actually puts in the gap is Int_-inf^0 rho dE =
    # trap_Nt_e * Et, NOT trap_Nt_e.  Passing N_T directly under-counts the
    # traps by 1/Et ~ 15x.  Divide by Et so the deck delivers the intended
    # total N_T = 7.5e17 cm^-3.
    nt_prefactor = NT_TRAP / et
    # the cathode (2.9 eV) sits 0.4 eV above the LUMO -> ohmic; the reference
    # holds n = 5e20 cm^-3 = N0/2 there, a half-filled Gaussian
    cnp = N0 / 2.0
    n = 0

    for folder, wf in sorted(ANODES.items()):
        outdir = os.path.join(HERE, "devices_%s" % folder)
        if not os.path.isdir(outdir):
            print("skipping missing folder", outdir)
            continue

        if folder in OHMIC_ANODES:
            # pinned ohmic anode: the reference holds p(0) = N0/2 at every bias
            anode_block = "model = ohmic-np\nnp = %.6e" % (N0 / 2.0)
            amodel = "ohmic"
        else:
            anode_block = "model = thermionic\nbarrier = %.3f" % (HOMO - wf)
            amodel = "thermionic"

        for label, mun_cm in sorted(MU0N.items()):
            deck = TEMPLATE.format(
                wf=wf, cwf=CATHODE_WF, amodel=amodel, mun_cm=mun_cm,
                outdir="out_%s_%s" % (folder, label),
                thick=THICK, eg=round(HOMO - LUMO, 6), xi=LUMO,
                n0="%.6e" % N0, sigma=SIGMA,
                mun="%.6e" % (mun_cm * 1e-4 / EGDM_C1),
                mup="%.6e" % (MU0P * 1e-4 / EGDM_C1),
                a="%.6e" % a, nt="%.6e" % nt_prefactor, et=et,
                lpre=LANGEVIN_PRE, anode_block=anode_block,
                cnp="%.6e" % cnp)
            path = os.path.join(outdir, "sim_%s_%s.ini" % (folder, label))
            with open(path, "w") as f:
                f.write(deck)
            n += 1
    print("wrote %d decks" % n)


if __name__ == "__main__":
    main()
